<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="servicegen"
    nsURI="http://www.csi.it/mddtools/servicegen" nsPrefix="servicegen">
  <eClassifiers xsi:type="ecore:EClass" name="SOABEModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseTypes" upperBound="-1"
        eType="#//BaseTypes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codProdotto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codComponente" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versioneProdotto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versioneComponente" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceimplementations"
        upperBound="-1" eType="#//ServiceImpl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceDefs" upperBound="-1"
        eType="ecore:EClass servicedef_metamodel.ecore#//ServiceDef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPlatform" eType="#//TargetPlatform"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseTypes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseTypes" upperBound="-1"
        eType="ecore:EClass typedef_metamodel.ecore#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceImpl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="provides" eType="ecore:EClass servicedef_metamodel.ecore#//ServiceDef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceComponent" eType="#//ServiceComponent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implCartridge" eType="#//LogicImplCartridge"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetPlatform">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="#//TargetPlatformCodes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TargetPlatformCodes">
    <eLiterals name="WLS92"/>
    <eLiterals name="JBoss43"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceComponent" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implCartridge" eType="#//LogicImplCartridge"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleSC" abstract="true" eSuperTypes="#//ServiceComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeSC" abstract="true" eSuperTypes="#//ServiceComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceBasedSC" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceSet" eType="ecore:EClass resources_metamodel.ecore#//ResourceSet"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceBasedSimpleSC" eSuperTypes="#//SimpleSC #//ResourceBasedSC"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrchestrationFlowCompositeSC" eSuperTypes="#//CompositeSC #//FlowBasedSC #//ResourceBasedSC"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlowBasedSC" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="LogicImplCartridge" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ManualImplCartridge" eSuperTypes="#//LogicImplCartridge"/>
  <eClassifiers xsi:type="ecore:EClass" name="CustomTemplateBasedImplCartridge" eSuperTypes="#//LogicImplCartridge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="template" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelBasedImplCartridge" abstract="true"
      eSuperTypes="#//LogicImplCartridge"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlowModelImplCartridge" eSuperTypes="#//ModelBasedImplCartridge"/>
</ecore:EPackage>
