<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="servicedef"
    nsURI="http://www.csi.it/mddtools/servicedef" nsPrefix="servicedef">
  <eClassifiers xsi:type="ecore:EClass" name="DocumentRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" upperBound="-1"
        eType="#//ServiceDef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codServizio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//ServiceBinding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monitorable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versione" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" eType="#//Types"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceType" eType="#//SrvTypeEnum"
        defaultValueLiteral="appl"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authLevel" eType="#//AuthLevelEnum"
        defaultValueLiteral="A0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceBinding" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codBinding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EJBPABinding" eSuperTypes="#//ServiceBinding"/>
  <eClassifiers xsi:type="ecore:EClass" name="SOAPPABRBinding" eSuperTypes="#//ServiceBinding"/>
  <eClassifiers xsi:type="ecore:EClass" name="WSFADBinding" eSuperTypes="#//ServiceBinding"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//Param" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opType" eType="#//OpTypeEnum"
        defaultValueLiteral="synch"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="ecore:EClass typedef_metamodel.ecore#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="throws" upperBound="-1"
        eType="ecore:EClass typedef_metamodel.ecore#//Exception"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="txType" eType="#//TXTypeEnum"
        defaultValueLiteral="noTX"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="since" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authorizedRoles" upperBound="-1"
        eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validator" eType="#//InputValidator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Param">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass typedef_metamodel.ecore#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validator" eType="#//ParamValidator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" eType="#//ValueConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OpTypeEnum">
    <eLiterals name="synch"/>
    <eLiterals name="asynch"/>
    <eLiterals name="notify"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Types">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="ecore:EClass typedef_metamodel.ecore#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseTypes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseTypes" upperBound="-1"
        eType="ecore:EClass typedef_metamodel.ecore#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TXTypeEnum">
    <eLiterals name="noTX"/>
    <eLiterals name="newLocalTX"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SrvTypeEnum">
    <eLiterals name="infr"/>
    <eLiterals name="appl"/>
    <eLiterals name="orch"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AuthLevelEnum">
    <eLiterals name="A0"/>
    <eLiterals name="A1"/>
    <eLiterals name="A2"/>
    <eLiterals name="A3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputValidator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" eType="#//ParamConstraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParamValidator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" eType="#//ValueConstraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueRangeConstraint" abstract="true"
      eSuperTypes="#//SimpleValueConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValueValorizationConstraint" eSuperTypes="#//SimpleValueConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mustNotBeNull" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomConstraint" eSuperTypes="#//SimpleValueConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkMethodName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelativeConstraint" eSuperTypes="#//SimpleValueConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValueConstraint" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleParamCoinstraint" eSuperTypes="#//ParamConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="#//Param"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" eType="#//ValueConstraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeParamConstraint" abstract="true"
      eSuperTypes="#//ParamConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//ParamConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANDParamConstraint" eSuperTypes="#//CompositeParamConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="ORParamConstraint" eSuperTypes="#//CompositeParamConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParamConstraint" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NOTParamConstraint" eSuperTypes="#//CompositeParamConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeValueConstraint" abstract="true"
      eSuperTypes="#//ValueConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//ValueConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANDValueConstraint" eSuperTypes="#//CompositeValueConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="ORValueConstraint" eSuperTypes="#//CompositeValueConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="NOTValueConstraint" eSuperTypes="#//CompositeValueConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleValueConstraint" abstract="true"
      eSuperTypes="#//ValueConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="EClass0"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContinuousRangeConstraint" eSuperTypes="#//ValueRangeConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerbound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperbound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscreteRangeConstraint" eSuperTypes="#//ValueRangeConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literals" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureConstraint" abstract="true" eSuperTypes="#//ValueConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeFeatureConstraint" abstract="true"
      eSuperTypes="#//FeatureConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleFeatureConstraint" eSuperTypes="#//FeatureConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" eType="#//ValueConstraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="ecore:EClass typedef_metamodel.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="ecore:EClass typedef_metamodel.ecore#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANDFeatureConstraint" eSuperTypes="#//CompositeFeatureConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="ORFeatureConstraint" eSuperTypes="#//CompositeFeatureConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="NOTFeatureConstraint" eSuperTypes="#//CompositeFeatureConstraint"/>
</ecore:EPackage>
