<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="typedef"
    nsURI="http://www.csi.it/mddtools/typedef" nsPrefix="typedef">
  <eClassifiers xsi:type="ecore:EClass" name="DocumentRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CSIDatatype" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="#//CSIDatatypeCodes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nillable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionuid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CSIDatatypeCodes">
    <eLiterals name="CSIInteger"/>
    <eLiterals name="CSIString"/>
    <eLiterals name="CSIFloat"/>
    <eLiterals name="CSIDouble"/>
    <eLiterals name="CSIBoolean"/>
    <eLiterals name="CSIDate"/>
    <eLiterals name="CSIByte"/>
    <eLiterals name="CSILong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedArray" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentType" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exception" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exceptionType" eType="#//CSIExceptionTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CSIExceptionTypes">
    <eLiterals name="USER"/>
    <eLiterals name="SYSTEM"/>
    <eLiterals name="UNRECOVERABLE"/>
  </eClassifiers>
</ecore:EPackage>
